// L1 system view in MARKDOWN mode.
//
// Renders Systems/<system_id>.md (written by frameworkScan as part of the
// framework-only scan) using the same MiniMarkdown pipeline as Lv2.  Internal
// member links navigate the active tab into Lv2 of the target blueprint
// (respecting the global viewMode — graph mode lands on Lv2BlueprintGraph,
// markdown mode on Lv2BlueprintFocus).
//
// The system file is generated by deriveSystemTag (first folder under /Game/)
// so when no scan has been run, we render an empty-state explaining how to
// create it instead of failing silently.

import React, { useEffect, useMemo } from 'react';
import { useVaultStore } from '../../store/useVaultStore';
import { useTabsStore } from '../../store/useTabsStore';
import { MiniMarkdown } from '../../utils/miniMarkdown';
import { NotesEditor } from '../notes/NotesEditor';
import { L1ScanButton } from './L1ScanButton';
import { useT } from '../../utils/i18n';

interface Props {
  systemId: string;
}

export const Lv1SystemMarkdown: React.FC<Props> = ({ systemId }) => {
  const t = useT();
  const relativePath = `Systems/${systemId}.md`;

  const projectRoot = useVaultStore((s) => s.projectRoot);
  const file = useVaultStore((s) => s.fileCache[relativePath]);
  const loadFile = useVaultStore((s) => s.loadFile);
  const files = useVaultStore((s) => s.files);
  const fileCache = useVaultStore((s) => s.fileCache);
  const navigate = useTabsStore((s) => s.navigateActive);

  useEffect(() => {
    if (!file) loadFile(relativePath);
  }, [relativePath, file, loadFile]);

  // Build a title → relativePath index for [[backlink]] resolution.  System
  // members are written with markdown-link syntax `[Name](../Blueprints/X.md)`
  // so MiniMarkdown will render them as md-external-link by default — but we
  // also catch [[Wiki]] style here in case the LLM rewrites the section.
  const titleToPath = useMemo(() => {
    const idx: Record<string, string> = {};
    for (const f of files) idx[f.title] = f.relative_path;
    for (const cached of Object.values(fileCache)) {
      const t = cached.frontmatter.title;
      if (typeof t === 'string') idx[t] = cached.relative_path;
    }
    return idx;
  }, [files, fileCache]);

  const onLinkClick = (target: string) => {
    const path = titleToPath[target];
    if (path) navigate({ level: 'lv2', relativePath: path }, target);
  };

  // Intercept clicks on relative-path member links so they navigate within the
  // shell instead of treating them as external URLs.  The system file uses
  // `../Blueprints/Foo.md` style links which MiniMarkdown renders as <a> with
  // href attributes — we capture those at the container level.
  const handleContainerClick = (e: React.MouseEvent<HTMLDivElement>) => {
    const target = e.target as HTMLElement;
    const a = target.closest('a.md-external-link');
    if (!a) return;
    const href = a.getAttribute('href');
    if (!href) return;
    if (/^https?:/.test(href)) return; // real external link, let it navigate
    e.preventDefault();
    // resolve `../Blueprints/Foo.md` against the current Systems/<id>.md path
    const resolved = resolveRelative(relativePath, href);
    const title = a.textContent ?? resolved;
    navigate({ level: 'lv2', relativePath: resolved }, title);
  };

  if (!projectRoot) {
    return (
      <div className="empty-state">
        <h2>{t({ en: 'No project root', zh: '未设置项目根目录' })}</h2>
        <p className="muted">{t({ en: 'Set a project root in Settings to read system intros.', zh: '请在设置中配置项目根目录以查看系统介绍。' })}</p>
      </div>
    );
  }
  if (!file) {
    return (
      <div className="empty-state">
        <p className="muted">
          {t({ en: 'Loading', zh: '正在加载' })} <code>{relativePath}</code>…
        </p>
        <p className="muted" style={{ fontSize: 'var(--fs-xs)' }}>
          {t({
            en: 'If this never resolves, run "Scan project structure" in Settings — it generates Systems/<id>.md alongside per-blueprint notes.',
            zh: '如果一直加载不出来，请在设置中运行 "扫描项目结构" — 它会在生成单个蓝图笔记的同时生成 Systems/<id>.md。',
          })}
        </p>
      </div>
    );
  }

  const fm = file.frontmatter;
  const memberCount = (fm.member_count as number | undefined) ?? 0;
  const analysisState = (fm.analysis_state as string | undefined) ?? 'skeleton';
  const displayName = (fm.title as string) ?? formatSystem(systemId);

  return (
    <div className="bp-focus">
      <div className="bp-focus-header">
        <div className="bp-focus-titlebar">
          <h1 className="bp-focus-title">{displayName}</h1>
          <div className="bp-focus-meta">
            <span className="pill pill-type">{t({ en: 'System', zh: '系统' })}</span>
            <span className="pill pill-parent">
              {t({ en: `${memberCount} members`, zh: `${memberCount} 个成员` })}
            </span>
            <span className={`pill pill-risk-${analysisState === 'llm' ? 'nominal' : 'elevated'}`}>
              {analysisState === 'llm'
                ? t({ en: 'LLM analyzed', zh: '已 LLM 分析' })
                : t({ en: 'skeleton', zh: '骨架' })}
            </span>
          </div>
          <L1ScanButton />
        </div>
      </div>

      <div className="bp-focus-body" onClick={handleContainerClick}>
        <div className="bp-focus-narrative">
          <MiniMarkdown source={file.aiSection} onLinkClick={onLinkClick} />
        </div>
        <NotesEditor relativePath={relativePath} initial={file.notes} />
      </div>
    </div>
  );
};

function formatSystem(id: string): string {
  if (id === '_unassigned') return 'Unassigned';
  if (id === '_overview') return 'Project Overview';
  return id.charAt(0).toUpperCase() + id.slice(1);
  // Note: this fallback only triggers when the .md has no `title` frontmatter.
  // Per-language label is handled by the LLM-written `title` field.
}

// Resolve `../Blueprints/Foo.md` against `Systems/combat.md` → `Blueprints/Foo.md`.
function resolveRelative(from: string, href: string): string {
  const base = from.split('/').slice(0, -1); // drop filename
  const parts = href.split('/');
  for (const p of parts) {
    if (p === '.' || p === '') continue;
    if (p === '..') base.pop();
    else base.push(p);
  }
  return base.join('/');
}
